### ISSUE TITLE
"Command python setup.py egg_info" failed with error code 1 in ...."

### ISSUE THREAD

**Issue by soumam007** [fossasia/badgeyay#215] opened 2017-10-01 06:32 UTC
Encountering an issue when using "pip install -r requirements.txt" in that I receive the error Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b2Dq_k/cairosvg/"
 I searched all over the place, but I cannot find a solution. Just looking for some feedback as to what the problem could be. I have also attached a screenshot of the console so that you can see the error as well. Thanks in advance!

![screenshot from 2017-10-01 11-57-53](https://user-images.githubusercontent.com/21683311/31052378-6605b4a0-a6a0-11e7-8e47-c6e6869db0b3.png)

**Comment by vaibhavsingh97** [comment] 2017-10-01 06:36
@soumam007 No issues here
```
[~ badgeyay]$ sudo -H pip install -r requirements.txt 
[sudo] password for vaibhav: 
Requirement already satisfied: click==6.7 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 1))
Requirement already satisfied: flask==0.12.2 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 2))
Requirement already satisfied: itsdangerous==0.24 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 3))
Requirement already satisfied: jinja2==2.9.6 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 4))
Requirement already satisfied: markupsafe==1.0 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 5))
Requirement already satisfied: werkzeug==0.12.2 in /usr/lib/python3.6/site-packages (from -r requirements/../app/requirements.txt (line 6))
Collecting wtforms==2.1 (from -r requirements/../app/requirements.txt (line 7))
  Downloading WTForms-2.1.zip (553kB)
    100% |████████████████████████████████| 563kB 439kB/s 
Collecting pyflakes==1.6.0 (from -r requirements/../app/requirements.txt (line 8))
  Downloading pyflakes-1.6.0-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 504kB/s 
Collecting flask-compress==1.4.0 (from -r requirements/../app/requirements.txt (line 9))
  Downloading Flask-Compress-1.4.0.tar.gz
Collecting selenium==3.5.0 (from -r requirements/../app/requirements.txt (line 10))
  Downloading selenium-3.5.0-py2.py3-none-any.whl (921kB)
    100% |████████████████████████████████| 921kB 368kB/s 
Collecting nose==1.3.7 (from -r requirements/../app/requirements.txt (line 11))
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 640kB/s 
Collecting pypdf2==1.26.0 (from -r requirements/../app/requirements.txt (line 12))
  Downloading PyPDF2-1.26.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 3.1MB/s 
Collecting cairosvg==2.0.3 (from -r requirements/../app/requirements.txt (line 13))
  Downloading CairoSVG-2.0.3.tar.gz
Requirement already satisfied: gunicorn==19.7.1 in /usr/lib/python3.6/site-packages (from -r requirements/prod.txt (line 2))
Collecting cairocffi (from cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
  Downloading cairocffi-0.8.0.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 243kB/s 
Requirement already satisfied: lxml in /usr/lib/python3.6/site-packages (from cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
Collecting cssselect (from cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
  Downloading cssselect-1.0.1-py2.py3-none-any.whl
Requirement already satisfied: pillow in /usr/lib/python3.6/site-packages (from cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
Collecting tinycss (from cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
  Downloading tinycss-0.4.tar.gz (87kB)
    100% |████████████████████████████████| 92kB 544kB/s 
Collecting cffi>=1.1.0 (from cairocffi->cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
  Downloading cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl (418kB)
    100% |████████████████████████████████| 419kB 441kB/s 
Requirement already satisfied: olefile in /usr/lib/python3.6/site-packages (from pillow->cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
Collecting pycparser (from cffi>=1.1.0->cairocffi->cairosvg==2.0.3->-r requirements/../app/requirements.txt (line 13))
  Using cached pycparser-2.18.tar.gz
Installing collected packages: wtforms, pyflakes, flask-compress, selenium, nose, pypdf2, pycparser, cffi, cairocffi, cssselect, tinycss, cairosvg
  Running setup.py install for wtforms ... done
  Running setup.py install for flask-compress ... done
  Running setup.py install for pypdf2 ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cairocffi ... done
  Running setup.py install for tinycss ... done
  Running setup.py install for cairosvg ... done
Successfully installed cairocffi-0.8.0 cairosvg-2.0.3 cffi-1.11.0 cssselect-1.0.1 flask-compress-1.4.0 nose-1.3.7 pycparser-2.18 pyflakes-1.6.0 pypdf2-1.26.0 selenium-3.5.0 tinycss-0.4 wtforms-2.1

```

**Comment by vaibhavsingh97** [comment] 2017-10-01 06:42
@soumam007 can we close this issue?

**Comment by gabru-md** [comment] 2017-10-01 06:48
@soumam007
Try `sudo apt-get update`
and
`suso apt-get upgrade`

**Comment by nanspro** [comment] 2017-10-01 07:14
@soumam007  sorry but the issue is with your PC, there is no fault in any of the configuration files.
It works fine for other users.
Shall we close this one @gabru-md ??

**Comment by soumam007** [comment] 2017-10-01 07:16
ok you may :)

**Comment by gabru-md** [comment] 2017-10-01 07:16
Yes sure.
Closing it.

**Closed by gabru-md** 2017-10-01 07:16 UTC

**Comment by soumam007** [comment] 2017-10-01 07:20
@gabru-md  but what shall i do, can you suggest something(working in fedora-26)

**Comment by ananyo2012** [comment] 2017-10-01 09:00
@soumam007 You are currently using python2 packages. But the python version for this app is python3. Try running `pip3 install -r requirements.txt` . You still may get an error saying `missing Header file Python.h` . In that case you need to install the `python-devel` package for Fedora. Install it using `dnf install python-devel`
