### ISSUE TITLE
Remove usage of pdftk and use pypdf

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#386] opened 2017-12-05 22:16 UTC
Presently the project used a non python library called pdftk to merge pdf files. So every time we need to merge pdf files we have to use pdftk as a separate process via subprocess as it is not available as a native python library. Also it involves the usage of some shell commands which creates problem for windows. However there is a very nice native python library present known as pypdf which allow us to work on pdf files including their merging. The objective of this issue is to remove the usage of pdftk and use pypdf in place of it.

*   View the usage of pdftk [here](https://github.com/fossasia/badgeyay/blob/development/app/merge_badges.py#L69) and [here](https://github.com/fossasia/badgeyay/blob/development/app/merge_badges.py#L72). This you have to replace with pypdf.
*   View how to do the same task (currently done by pdftk) using pypdf [here](https://github.com/fossasia/badgeyay/blob/development/app/merge_badges_v2.py#L52) and [here](https://github.com/fossasia/badgeyay/blob/development/app/merge_badges_v2.py#L65).

**Comment by ParthS007** [comment] 2017-12-05 23:50
working on it :+1:

**Comment by djmgit** [comment] 2017-12-06 04:00
@mariobehling  @ParthS007 This is an duplicate issue of #380 
@ParthS007 #380 has been added as a GCI task. So I would suggest you to mentor this task and review student PR.
You may consider working on other non-GCI issues

**Comment by djmgit** [comment] 2017-12-06 04:00
@mariobehling should I close it as it is a duplicate

**Comment by ParthS007** [comment] 2017-12-06 04:03
Yes @djmgit ,I think you can close it :+1:

**Comment by raju249** [comment] 2017-12-09 05:25
Duplicate of #380. Please close this.
Thanks

**Closed** 2017-12-09 05:26 UTC
