### ISSUE TITLE
footer not at the bottom of page

### ISSUE THREAD

**Issue by sounak98** [fossasia/badgeyay#118] opened 2017-09-19 05:12 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Footer is not how it should be.
![screenshot from 2017-09-19 10-38-29](https://user-images.githubusercontent.com/22390515/30576645-e7e01b88-9d26-11e7-95ff-fc968fcda34d.png)

**Expected behavior:**

Footer should be at the bottom of the page.

I'm working on this.

**Comment by gabru-md** [comment] 2017-09-19 05:15
@sounak98
Please have a look here : #109
I guess it is already solved.

**Comment by S2606** [comment] 2017-09-19 05:15
@sounak98 I am running it on my local machine and this error isnt happening. Are you running on updated branch?

**Comment by sounak98** [comment] 2017-09-19 05:20
@S2606 The updated branch had this issue. I am running it on my local machine.

**Comment by gabru-md** [comment] 2017-09-19 05:24
@S2606
These changes have already been done and are reflected on badgeyay-dev.herokuapp.com
I believe this issue to be irrelevant.
But i would still ask for your consideration.
PS : jajodiaraghav

**Comment by sounak98** [comment] 2017-09-19 05:43
Yeah, I know. The changes are reflected on badgeyay-dev.herokuapp.com. It is not reflecting on my local machine though. It'll be good if you guys can check once.

**Comment by S2606** [comment] 2017-09-19 05:46
@sounak98 I have checked in my local machine(its working fine) and it looks as if your local machine isnt updated(as far as i know). please check your commit history by using `git log --oneline` and match it with the last commit for more information.

**Comment by jajodiaraghav** [comment] 2017-09-19 05:48
I am unable to reproduce the issue. It looks fine on my local machine as well as on heroku deploy

**Closed** 2017-09-19 05:49 UTC
