### ISSUE TITLE
Route does not change

### ISSUE THREAD

**Issue by RisingGeek** [fossasia/badgeyay#2141] opened 2019-10-03 18:40 UTC
**Describe the bug**
Route does not change to `/create-badges` on clicking the button.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [http://badgeyay.com](url)
2. Login
3. Click on create Badge

**Expected behaviour**
Route should be changed and form to create badge should be present.

**Expected behaviour**
Route is not changed. Sometimes, route changes but the form is not loaded. Refer screenshot.

![Screenshot from 2019-10-03 23-57-02](https://user-images.githubusercontent.com/37294158/66154493-351c0b00-e63b-11e9-80ae-a728aaabcc24.png)

**Desktop:**
 - OS: [Linux]
 - Browser [chrome]
 - Version [77]

**Comment by kushthedude** [comment] 2019-10-04 09:09
Duplicate of #2119

**Closed by kushthedude** 2019-10-04 09:09 UTC
