### ISSUE TITLE
Download fail:NO FILE

### ISSUE THREAD

**Issue by nanspro** [fossasia/badgeyay#30] opened 2017-09-12 08:30 UTC
What is the workflow of website,when i uploaded png and csv files it says badge is ready download as pdf but it shows download fail NO FILE.
![workspace 1_007](https://user-images.githubusercontent.com/24641089/30315699-78fec1ec-97c2-11e7-8445-08b3c6c456b2.png)

However the uploaded files are downloaded in uploads folder but there is no badge so how are we returning user it's badge as pdf.
![workspace 1_008](https://user-images.githubusercontent.com/24641089/30315772-ab37148e-97c2-11e7-8f42-4dda45fe4ff9.png)

**Comment by niccokunzmann** [comment] 2017-09-12 08:34
Can you check again with the updated version? #24 could have resolved this.

**Comment by nanspro** [comment] 2017-09-12 08:47
i tried again 
i uploaded camera.png.csv and camera.png (after removing them from uploads) then again it said download failed:no file and in uploads section it gets both uploaded files
Also what is generate_badges.py doing in uploads directory is it supposed to automatically run on uploaded files and return pdf ?

**Comment by niccokunzmann** [comment] 2017-09-12 08:55
@jajodiaraghav Do you have any ideas?

**Comment by jajodiaraghav** [comment] 2017-09-12 09:28
Hi @nanspro I am unable to reproduce the issue. I tried all the possible use cases and I received the downloadable pdf file. It works perfectly fine for me.
Possible reasons:
1. Did you rebase and pull the latest changes?
2. Please check if you have write permissions for the uploads folder


> what is generate_badges.py doing in uploads directory
The generate_badges file pulls all the csv files in the uploads folder and generates a pdf. I was thinking of moving it from uploads folder. It would be nice if someone could work on it.

**Comment by nanspro** [comment] 2017-09-12 09:28
My branch was few commits behind now it is working

**Closed** 2017-09-12 09:29 UTC
