### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by parimatrix** [fossasia/badgeyay#73] opened 2017-09-16 19:23 UTC
**I'm submitting a ...**  (check one with "x")
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
On uploading any sample data and clicking upload, the site displays 500 Internal Server Error. 

**Expected behavior:**
Should create the required badges.

**Comment by niccokunzmann** [comment] 2017-09-16 20:41
Can you show the error? The traceback and maybe a screenshot of this? Is there any more text? If you start the app, indebug mode, there could be even more output. Anything would help.

**Comment by parimatrix** [comment] 2017-09-16 20:46
@niccokunzmann Hi ! I have not setup the repo on my own. So I can't send you the detailed error. But I can give you a screenshot of the screen the user sees.
![screenshot 17](https://user-images.githubusercontent.com/25114873/30515894-3d329f5a-9b4e-11e7-8ae3-a76f3780390d.png)

**Comment by niccokunzmann** [comment] 2017-09-16 20:50
@parimatrix Great. If you set up the repo for yourself, you would go through the first steps, you go either way to contribute code. Would you like to set it up, retry what you do and see if the error still exists?
If you have any problems during that, you can post as much information as you can git to gitter or here.

**Comment by gabru-md** [comment] 2017-09-17 03:49
I've provided with a fix for this very issue.
It is caused by a missing badges folder. The PR has been merged but has not been deployed yet i guess.
Because that PR seems to have fix this bug.
Please see : #59

**Comment by jajodiaraghav** [comment] 2017-09-17 07:59
I think this can be closed now. We have the error fixed :)

**Closed** 2017-09-17 08:38 UTC
