### ISSUE TITLE
Update generate-badges.py so that it can be used as a library

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#385] opened 2017-12-05 22:15 UTC
Badgeyay uses generate-badges.py to generate badges from csv files. Presently generate-badges.py can only be used as a stand alone module and cannot be used by importing from another file. That is, currently if we want to use that file from another file then we have to use python subprocess or os module which is kind of hacky. The object of this task is to update generate-badges.py so that it can be imported from another file as a library. In short, we require an function as an interface which can be imported from another file and used. At the same time provision should be kept for using the file as a stand alone module as well so that the existing system does not break.

**Comment by S2606** [comment] 2017-12-05 23:48
Can i work on this @mariobehling ??

**Comment by harshit98** [comment] 2017-12-05 23:50
Please go ahead @S2606 👍

**Comment by djmgit** [comment] 2017-12-06 04:02
@mariobehling @S2606 This is an duplicate issue. The same issue is already present and it has been marked as a GCI task. 
@S2606 you may consider reviewing student's PR who will be working on this. You may consider working on other open issues.

**Comment by djmgit** [comment] 2017-12-06 04:04
@mariobehling should I close this issue as this is an duplicate of #379

**Comment by raju249** [comment] 2017-12-09 10:09
Please close this issue. Duplicate of #379 
Thanks

**Closed** 2017-12-11 12:15 UTC
