### ISSUE TITLE
Irrespective of data change, generated badges are same

### ISSUE THREAD

**Issue by rupav** [fossasia/badgeyay#582] opened 2018-02-08 07:18 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Expected behavior:**

No. of badges should be twice the entries.

**Steps to reproduce:**
Enter 4 entries in badgeyay.com, now generate badges, only 2 badges are present instead of 8!

** I am working on it **

**Comment by gabru-md** [comment] 2018-02-08 07:24
@rupav there is no such issue.
Badges are made perfectly fine and in right numbers.

**Comment by gabru-md** [comment] 2018-02-08 07:25
![screenshot_20180208-125433](https://user-images.githubusercontent.com/25414121/35960318-46a81b94-0ccf-11e8-91fc-db4069a056a1.png)
Incase you need a screenshot.

**Comment by vaibhavsingh97** [comment] 2018-02-08 07:36
Please check the PDF: 
[black_futuristic-png-csv-badges.pdf](https://github.com/fossasia/badgeyay/files/1706097/black_futuristic-png-csv-badges.pdf)

**Comment by gabru-md** [comment] 2018-02-08 07:44
![screenshot_20180208-131350](https://user-images.githubusercontent.com/25414121/35961001-f941133a-0cd1-11e8-8c57-25f09f5224f9.png)

@vaibhavsigh97 please take a look. This is your pdf that I downloaded.

**Comment by rupav** [comment] 2018-02-08 07:49
yes its working fine on google chrome.I tried on firefox (my default browser), and its producing same color badges what so ever you give input: 
![2018-02-08 6](https://user-images.githubusercontent.com/20624380/35961084-59bfdbce-0cd2-11e8-8cdb-9e4dbca25df9.png)
Will look into this, maybe clearning cache will work, close this issue once get the results fine
@gabru-md @vaibhavsingh97

**Comment by gabru-md** [comment] 2018-02-08 07:50
Try cache cleaning.
Maybe it helps.

**Comment by gabru-md** [comment] 2018-02-08 07:53
@rupav please look into the `dev console` maybe there are some errors down there which might help you debug this problem ?
If you get any please post them here so that we can also look into this.

**Comment by rupav** [comment] 2018-02-08 07:54
![2018-02-08 7](https://user-images.githubusercontent.com/20624380/35961349-51676432-0cd3-11e8-89f1-754e511bf2ca.png)
Getting into a 404 error, will try again later then. Cleared cache completely.

**Comment by rupav** [comment] 2018-02-08 07:56
![2018-02-08 8](https://user-images.githubusercontent.com/20624380/35961423-a915c48a-0cd3-11e8-90d8-b6f666cd5ab5.png)
Its good now, working as expected...
closing this then 😅

**Comment by gabru-md** [comment] 2018-02-08 07:57
How did you resolve it?
Please state it down here so that anybody who faces this error can go through your way! 
Ping @rupav

**Comment by vaibhavsingh97** [comment] 2018-02-08 07:59
@rupav I too cleared cache completely. But the issue is till the same

**Comment by rupav** [comment] 2018-02-08 08:00
clearing cache... , @vaibhavsingh97 ok I will look into this. Send you a response by evening.  👍

**Comment by rupav** [comment] 2018-02-08 13:19
@vaibhavsingh97 in chrome, clicking on `download as pdf`, the badges directly gets saved to your downloads directory ?
In firefox, this is not happening for me and I am directed to a webpage which have the pdf, to download explicitly (maybe I have changed firefox settings).

**Comment by sagar-kalra** [comment] 2018-03-18 08:47
@rupav you should change your firefox settings. Check this out https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file, this solves the problem.

**Comment by gabru-md** [comment] 2018-03-19 17:21
close this ?

**Comment by ParthS007** [comment] 2018-03-19 17:21
closing this as Its working fine :+1:

**Closed by ParthS007** 2018-03-19 17:21 UTC
Labels: Bug
