### ISSUE TITLE
Test the main workflows

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#93] opened 2017-09-17 12:37 UTC
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**

Currently, we have basic testing.

**Expected behavior:**

Please test the main workflows:

1. Insert data as
  - [ ] (1.1) json
  - [ ] (1.2) csv file
  - [ ] (1.3) eventbrite link
2. for each request downloading as
  - [ ] (2.1) svg
  - [ ] (2.2) zip
  - [ ] (2.3) pdf
3. submit the data
4. download what is expected

To do that, please create a new test file.
I might not know all the versions, please correct  me.

**Comment by jajodiaraghav** [comment] 2017-09-17 13:59
Claiming 🚀

**Comment by jajodiaraghav** [comment] 2017-09-25 04:34
Closing as a duplicate of #122

**Closed by jajodiaraghav** 2017-09-25 04:34 UTC
Labels: test-and-quality
