### ISSUE TITLE
Badges not found

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#168] opened 2017-09-23 15:56 UTC
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/18497513/30774768-bb00f434-a0a5-11e7-860f-ce77795085dd.png)
![image](https://user-images.githubusercontent.com/18497513/30774760-8ccfda9e-a0a5-11e7-97eb-bb6c859b0af4.png)

**Expected behavior:**
It should be downloaded!

**Comment by S2606** [comment] 2017-09-23 15:57
@niccokunzmann @jajodiaraghav @djmgit @gabru-md @vaibhavsingh97 @nanspro

**Comment by gabru-md** [comment] 2017-09-23 16:29
IDK how this issue got closed : https://github.com/fossasia/badgeyay/issues/139
It is almost as same as this one.
@S2606 Actually the files are actually not created because the csv file is not read.
I was working on it but it got closed somehow by a PR.

**Comment by gabru-md** [comment] 2017-09-23 16:29
I would like to work on this with @S2606 .
Are you okay with collaborating on this issue? @S2606

**Comment by S2606** [comment] 2017-09-23 16:34
@gabru-md I am ready to collaborate

**Comment by vaibhavsingh97** [comment] 2017-09-23 17:04
@S2606 yeah, it's an issue. I forgot to open 😛

**Comment by gabru-md** [comment] 2017-09-24 08:05
Wrongly Closed by #171 
Therefore Reopened

**Comment by nanspro** [comment] 2017-09-25 19:46
I don't understand the issue,it's working totally fine for me.
![workspace 1_031](https://user-images.githubusercontent.com/24641089/30827575-335d19e0-a258-11e7-91a4-9ba66cb536cd.png)

**Comment by nanspro** [comment] 2017-09-25 19:46
@gabru-md  @S2606

**Comment by vaibhavsingh97** [comment] 2017-09-25 19:58
@nanspro Click on Download as PDF and you will land on that mentioned page 😄

**Comment by nanspro** [comment] 2017-09-25 20:00
![workspace 1_032](https://user-images.githubusercontent.com/24641089/30828131-3f570268-a25a-11e7-83b2-a54e1e2f3009.png)
It seems to be working fine Can you please check it again @vaibhavsingh97 .
![workspace 1_033](https://user-images.githubusercontent.com/24641089/30828133-424640ce-a25a-11e7-8a45-71f8271dfa80.png)

**Comment by vaibhavsingh97** [comment] 2017-09-25 20:05
@nanspro 
When we open `http://127.0.0.1:5000/`
![image](https://user-images.githubusercontent.com/8705386/30828271-a1af950c-a22c-11e7-8511-30904225c844.png)
After uploading relevant csv and click on upload
![image](https://user-images.githubusercontent.com/8705386/30828287-b232453c-a22c-11e7-87d5-d9d0c530a8cc.png)
After generation of badge when we open the generated pdf
![image](https://user-images.githubusercontent.com/8705386/30828296-b6b5f590-a22c-11e7-9eef-62b9223dd669.png)

**Comment by nanspro** [comment] 2017-09-25 20:47
![workspace 1_034](https://user-images.githubusercontent.com/24641089/30830184-bdf23b78-a260-11e7-8d47-e5afebeb8293.png)
After changing dots with '-' it gave correct output but again i don't understand when i clicked on downloaded file it shows the pdf.

**Comment by nanspro** [comment] 2017-09-27 21:43
@vaibhavsingh97  are you still facing this issue??

**Comment by vaibhavsingh97** [comment] 2017-09-27 21:44
@nanspro Yes 😞

**Comment by jajodiaraghav** [comment] 2017-10-08 09:29
Can someone please check if the issue is fixed or not.

**Comment by vaibhavsingh97** [comment] 2017-10-08 10:56
@jajodiaraghav Issue still persist on my system 😞

**Comment by djmgit** [comment] 2017-10-08 11:14
@vaibhavsingh97  what is your terminal showing? Are you able to generate badges manually by excuting merge_badges.py from terminal?

**Comment by vaibhavsingh97** [comment] 2017-10-08 11:32
Basically it fails to recognize location of rsvg-convert
```
Traceback (most recent call last):
  File "/home/vaibhav/badgeyay/app/merge_badges.py", line 16, in <module>
    if subprocess.run('which rsvg-convert') != 0:
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'which rsvg-convert'
127.0.0.1 - - [08/Oct/2017 16:58:38] "POST /upload HTTP/1.1" 302 -
127.0.0.1 - - [08/Oct/2017 16:58:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Oct/2017 16:58:41] "GET /static/badges/businesspass-png-csv-badges.pdf HTTP/1.1" 404 -
```
But on finding file in my system, it's able to find location of package 
```
 $ which rsvg-convert
/usr/bin/rsvg-convert
```

**Comment by vaibhavsingh97** [comment] 2017-10-09 19:57
@S2606 Closing since this issue is fixed. Will reopen when it will occur again 😄

**Closed by vaibhavsingh97** 2017-10-09 19:57 UTC
Labels: hacktoberfest
