### ISSUE TITLE
Unable to delete Badge 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/badgeyay#1702] opened 2018-09-14 19:49 UTC
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

![screenshot from 2018-09-15 01-19-06](https://user-images.githubusercontent.com/17084322/45571896-66396a00-b885-11e8-91c6-adf9bbdb6f41.png)

**Expected behaviour:**

**Steps to reproduce:**

**Comment by ParthS007** [comment] 2018-09-16 05:37
@sk9331657  Please fill the Issue template completely and mention the reason for the error. See the Server logs for details. Please try to reproduce Issue on the main site, **not on your local machine.** 

I have tried on the main site and faced no problem with **Deleting badge**. Please follow the best practices and follow the program guidelines.

Closing this :+1:

**Closed by ParthS007** 2018-09-16 05:37 UTC
